### PR TITLE
Feat/issue 34/create button component

### LINKED ISSUE #34: Create Button component
A Button component that is used to replace all native usage of the `button` HTML element

### PR DESCRIPTION
**Pull request by TazDeCoder**
This PR resolves #34

### CODE REVIEW

**Comment by TazDeCoder** [comment]
Screenshot of button component

**Review by Remi-dee — COMMENTED** [review]
LG

**Review by Remi-dee — COMMENTED** [review]
LG

**Comment by TazDeCoder** [comment]
If it "LG" then you can please approve the PR - thanks

**Review by Remi-dee — APPROVED** [review]

**Comment by Remi-dee** [comment]
> If it "LG" then you can please approve the PR - thanks

Pardon me,  I thought i used approve review.
all done now.

**Pull request merged**
